name: Artipie Benchmarks

on:
  create:
    tags:
      - .*
  push:
    branches:
      - .*

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    needs: docker-publish
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Run benchmarks
        uses: brastak/ga-actions@master
        with:
          aws-access-key: '${{ secrets.PERF_AWS_ACCESS_KEY }}'
          aws-secret-key: '${{ secrets.PERF_AWS_SECRET_KEY }}'
          adapter: 'files'
          scenario: 'upload-files.jmx'
          version: '${{ env.RELEASE_VERSION }}'
      - name: Publish reports
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: report
          TARGET_FOLDER: ${{ env.RELEASE_VERSION }}/files/upload
