name: Artipie Benchmarks

on:
  release:
    types: [published]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Run benchmarks
        uses: brastak/ga-actions@master
        with:
          aws-access-key: '${{ secrets.PERF_AWS_ACCESS_KEY }}'
          aws-secret-key: '${{ secrets.PERF_AWS_SECRET_KEY }}'
          adapter: 'files'
          scenario: 'upload-files.jmx'
          version: 'latest'
      - name: Check results
        run: ls -la
      - name: Publish reports
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: report
          TARGET_FOLDER: ${{ github.event.release.tag_name }}/files/upload
